language: node_js

node_js:
- lts/*

script:
- ng lint
- npm run test-headless

deploy:
  provider: s3
  bucket: dw-portfolio-frontend
  local-dir: dist
  upload_dir: .
  acl: 'private'
  on:
    repo: footballencarta/portfolio-frontend
    branch: main
  skip_cleanup: 'true'

after_success:
- test $TRAVIS_BRANCH = "main" &&
  test $TRAVIS_PULL_REQUEST = "false" &&
  bash <(curl -s https://codecov.io/bash)
