language: node_js

node_js:
- lts/*

script:
- ng lint
- npm run test-headless
- ng build --prod

deploy:
  provider: s3
  bucket: dw-portfolio-frontend
  upload_dir: .
  local_dir: dist
  acl: 'private'
  on:
    repo: footballencarta/portfolio-frontend
    branch: main
  cleanup: false
  edge: true

after_success:
- test $TRAVIS_BRANCH = "main" &&
  test $TRAVIS_PULL_REQUEST = "false" &&
  bash <(curl -s https://codecov.io/bash)
