language: nodejs
php:
  - 14

jobs:
  include:
    - stage: test
      script:
        - ng lint
        - npm run test-headless
    - stage: deploy
      script:
        - composer install --no-dev --no-scripts
        - npx serverless deploy

stages:
  - test
  - name: deploy
    if: (branch = main) AND (NOT (type IN (pull_request)))

after_success:
    - test $TRAVIS_BRANCH = "main" &&
      test $TRAVIS_PULL_REQUEST = "false" &&
      bash <(curl -s https://codecov.io/bash)
